services:
  website:
    build: website
    ports:
      - 3000:3000
    networks:
      - frontend_network
networks:
  frontend_network:
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"
    driver: bridge